replicaCount: 2

image:
  repository: selena/users-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9065

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: users.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

app:
  env: "development"
  debug: "true"

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

persistence:
  enabled: true
  size: 1Gi
  storageClass: standard

db:
  host: "users-db-service"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "users_db" 

runMode: "k8s"